# Generated by Django 3.1 on 2020-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='details',
            new_name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
